steps:
    - name: gcr.io/cloud-builders/docker
    - args: ['build', '-t', 'gcr.io/_$IMAGE_NAME', '.']
    - name: gcr.io/cloud-builders/docker
    - args: ['push', 'gcr.io/_$IMAGE_NAME']
    - name: gcr.io/cloud-builders/gcloud
    - args: ['run', 'services', 'update', '$_CLOUD_RUN_SERVICE_NAME', '--image=gcr.io/_$IMAGE_NAME:latest', '--region=us-east4']
    options:
      logging: CLOUD_LOGGING_ONLY
