steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - $_IMAGE_NAME
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_IMAGE_NAME
    dir: ui
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - services
      - update
      - $_CLOUD_RUN_SERVICE_NAME
      - '--image=$_IMAGE_NAME:latest'
      - '--region=us-east4'
options:
  logging: CLOUD_LOGGING_ONLY
